language: cpp
compiler:
- gcc
before_install:
- git submodule update --init --recursive
install:
- wget https://downloads.lede-project.org/releases/17.01.0-rc2/targets/kirkwood/generic/lede-sdk-17.01.0-rc2-kirkwood_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64.tar.xz -O - | tar xJf - -C .
script:
- export PATH=$PATH:../lede-sdk-17.01.0-rc2-kirkwood_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/staging_dir/toolchain-arm_xscale_gcc-5.4.0_musl-1.1.16_eabi/bin
- export STAGING_DIR=../lede-sdk-17.01.0-rc2-kirkwood_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/staging_dir/toolchain-arm_xscale_gcc-5.4.0_musl-1.1.16_eabi
- cd pdnsd
- ./configure --build=x86_64-unknown-linux-gnu -host=arm-openwrt-linux-muslgnueabi
- make
